"""Spanish numbers data for diminumero."""

NUMBERS = {
    1: "uno",
    2: "dos",
    3: "tres",
    4: "cuatro",
    5: "cinco",
    6: "seis",
    7: "siete",
    8: "ocho",
    9: "nueve",
    10: "diez",
    11: "once",
    12: "doce",
    13: "trece",
    14: "catorce",
    15: "quince",
    16: "dieciséis",
    17: "diecisiete",
    18: "dieciocho",
    19: "diecinueve",
    20: "veinte",
    21: "veintiuno",
    22: "veintidós",
    23: "veintitrés",
    24: "veinticuatro",
    25: "veinticinco",
    26: "veintiséis",
    27: "veintisiete",
    28: "veintiocho",
    29: "veintinueve",
    30: "treinta",
    31: "treinta y uno",
    32: "treinta y dos",
    33: "treinta y tres",
    34: "treinta y cuatro",
    35: "treinta y cinco",
    36: "treinta y seis",
    37: "treinta y siete",
    38: "treinta y ocho",
    39: "treinta y nueve",
    40: "cuarenta",
    41: "cuarenta y uno",
    42: "cuarenta y dos",
    43: "cuarenta y tres",
    44: "cuarenta y cuatro",
    45: "cuarenta y cinco",
    46: "cuarenta y seis",
    47: "cuarenta y siete",
    48: "cuarenta y ocho",
    49: "cuarenta y nueve",
    50: "cincuenta",
    51: "cincuenta y uno",
    52: "cincuenta y dos",
    53: "cincuenta y tres",
    54: "cincuenta y cuatro",
    55: "cincuenta y cinco",
    56: "cincuenta y seis",
    57: "cincuenta y siete",
    58: "cincuenta y ocho",
    59: "cincuenta y nueve",
    60: "sesenta",
    61: "sesenta y uno",
    62: "sesenta y dos",
    63: "sesenta y tres",
    64: "sesenta y cuatro",
    65: "sesenta y cinco",
    66: "sesenta y seis",
    67: "sesenta y siete",
    68: "sesenta y ocho",
    69: "sesenta y nueve",
    70: "setenta",
    71: "setenta y uno",
    72: "setenta y dos",
    73: "setenta y tres",
    74: "setenta y cuatro",
    75: "setenta y cinco",
    76: "setenta y seis",
    77: "setenta y siete",
    78: "setenta y ocho",
    79: "setenta y nueve",
    80: "ochenta",
    81: "ochenta y uno",
    82: "ochenta y dos",
    83: "ochenta y tres",
    84: "ochenta y cuatro",
    85: "ochenta y cinco",
    86: "ochenta y seis",
    87: "ochenta y siete",
    88: "ochenta y ocho",
    89: "ochenta y nueve",
    90: "noventa",
    91: "noventa y uno",
    92: "noventa y dos",
    93: "noventa y tres",
    94: "noventa y cuatro",
    95: "noventa y cinco",
    96: "noventa y seis",
    97: "noventa y siete",
    98: "noventa y ocho",
    99: "noventa y nueve",
    100: "cien",
    101: "ciento uno",
    104: "ciento cuatro",
    107: "ciento siete",
    112: "ciento doce",
    120: "ciento veinte",
    126: "ciento veintiséis",
    128: "ciento veintiocho",
    131: "ciento treinta y uno",
    133: "ciento treinta y tres",
    145: "ciento cuarenta y cinco",
    147: "ciento cuarenta y siete",
    149: "ciento cuarenta y nueve",
    158: "ciento cincuenta y ocho",
    166: "ciento sesenta y seis",
    168: "ciento sesenta y ocho",
    172: "ciento setenta y dos",
    174: "ciento setenta y cuatro",
    181: "ciento ochenta y uno",
    182: "ciento ochenta y dos",
    190: "ciento noventa",
    194: "ciento noventa y cuatro",
    195: "ciento noventa y cinco",
    196: "ciento noventa y seis",
    200: "doscientos",
    204: "doscientos cuatro",
    205: "doscientos cinco",
    209: "doscientos nueve",
    213: "doscientos trece",
    215: "doscientos quince",
    218: "doscientos dieciocho",
    228: "doscientos veintiocho",
    242: "doscientos cuarenta y dos",
    243: "doscientos cuarenta y tres",
    247: "doscientos cuarenta y siete",
    257: "doscientos cincuenta y siete",
    260: "doscientos sesenta",
    262: "doscientos sesenta y dos",
    264: "doscientos sesenta y cuatro",
    266: "doscientos sesenta y seis",
    267: "doscientos sesenta y siete",
    268: "doscientos sesenta y ocho",
    276: "doscientos setenta y seis",
    283: "doscientos ochenta y tres",
    297: "doscientos noventa y siete",
    304: "trescientos cuatro",
    315: "trescientos quince",
    317: "trescientos diecisiete",
    318: "trescientos dieciocho",
    321: "trescientos veintiuno",
    324: "trescientos veinticuatro",
    325: "trescientos veinticinco",
    326: "trescientos veintiséis",
    329: "trescientos veintinueve",
    334: "trescientos treinta y cuatro",
    335: "trescientos treinta y cinco",
    339: "trescientos treinta y nueve",
    351: "trescientos cincuenta y uno",
    353: "trescientos cincuenta y tres",
    358: "trescientos cincuenta y ocho",
    370: "trescientos setenta",
    371: "trescientos setenta y uno",
    372: "trescientos setenta y dos",
    374: "trescientos setenta y cuatro",
    375: "trescientos setenta y cinco",
    377: "trescientos setenta y siete",
    382: "trescientos ochenta y dos",
    385: "trescientos ochenta y cinco",
    397: "trescientos noventa y siete",
    401: "cuatrocientos uno",
    406: "cuatrocientos seis",
    423: "cuatrocientos veintitrés",
    424: "cuatrocientos veinticuatro",
    432: "cuatrocientos treinta y dos",
    433: "cuatrocientos treinta y tres",
    445: "cuatrocientos cuarenta y cinco",
    449: "cuatrocientos cuarenta y nueve",
    453: "cuatrocientos cincuenta y tres",
    464: "cuatrocientos sesenta y cuatro",
    468: "cuatrocientos sesenta y ocho",
    471: "cuatrocientos setenta y uno",
    474: "cuatrocientos setenta y cuatro",
    480: "cuatrocientos ochenta",
    483: "cuatrocientos ochenta y tres",
    488: "cuatrocientos ochenta y ocho",
    489: "cuatrocientos ochenta y nueve",
    490: "cuatrocientos noventa",
    491: "cuatrocientos noventa y uno",
    495: "cuatrocientos noventa y cinco",
    506: "quinientos seis",
    509: "quinientos nueve",
    511: "quinientos once",
    530: "quinientos treinta",
    533: "quinientos treinta y tres",
    539: "quinientos treinta y nueve",
    546: "quinientos cuarenta y seis",
    560: "quinientos sesenta",
    565: "quinientos sesenta y cinco",
    570: "quinientos setenta",
    571: "quinientos setenta y uno",
    574: "quinientos setenta y cuatro",
    580: "quinientos ochenta",
    601: "seiscientos uno",
    606: "seiscientos seis",
    612: "seiscientos doce",
    613: "seiscientos trece",
    618: "seiscientos dieciocho",
    620: "seiscientos veinte",
    622: "seiscientos veintidós",
    642: "seiscientos cuarenta y dos",
    644: "seiscientos cuarenta y cuatro",
    647: "seiscientos cuarenta y siete",
    650: "seiscientos cincuenta",
    652: "seiscientos cincuenta y dos",
    653: "seiscientos cincuenta y tres",
    659: "seiscientos cincuenta y nueve",
    666: "seiscientos sesenta y seis",
    667: "seiscientos sesenta y siete",
    671: "seiscientos setenta y uno",
    675: "seiscientos setenta y cinco",
    681: "seiscientos ochenta y uno",
    692: "seiscientos noventa y dos",
    698: "seiscientos noventa y ocho",
    699: "seiscientos noventa y nueve",
    704: "setecientos cuatro",
    705: "setecientos cinco",
    711: "setecientos once",
    714: "setecientos catorce",
    717: "setecientos diecisiete",
    719: "setecientos diecinueve",
    724: "setecientos veinticuatro",
    734: "setecientos treinta y cuatro",
    741: "setecientos cuarenta y uno",
    743: "setecientos cuarenta y tres",
    744: "setecientos cuarenta y cuatro",
    751: "setecientos cincuenta y uno",
    755: "setecientos cincuenta y cinco",
    756: "setecientos cincuenta y seis",
    757: "setecientos cincuenta y siete",
    759: "setecientos cincuenta y nueve",
    764: "setecientos sesenta y cuatro",
    766: "setecientos sesenta y seis",
    772: "setecientos setenta y dos",
    778: "setecientos setenta y ocho",
    787: "setecientos ochenta y siete",
    793: "setecientos noventa y tres",
    797: "setecientos noventa y siete",
    799: "setecientos noventa y nueve",
    800: "ochocientos",
    802: "ochocientos dos",
    805: "ochocientos cinco",
    815: "ochocientos quince",
    819: "ochocientos diecinueve",
    822: "ochocientos veintidós",
    828: "ochocientos veintiocho",
    834: "ochocientos treinta y cuatro",
    836: "ochocientos treinta y seis",
    845: "ochocientos cuarenta y cinco",
    847: "ochocientos cuarenta y siete",
    848: "ochocientos cuarenta y ocho",
    850: "ochocientos cincuenta",
    855: "ochocientos cincuenta y cinco",
    859: "ochocientos cincuenta y nueve",
    860: "ochocientos sesenta",
    863: "ochocientos sesenta y tres",
    866: "ochocientos sesenta y seis",
    878: "ochocientos setenta y ocho",
    882: "ochocientos ochenta y dos",
    887: "ochocientos ochenta y siete",
    891: "ochocientos noventa y uno",
    892: "ochocientos noventa y dos",
    900: "novecientos",
    904: "novecientos cuatro",
    908: "novecientos ocho",
    909: "novecientos nueve",
    916: "novecientos dieciséis",
    917: "novecientos diecisiete",
    926: "novecientos veintiséis",
    927: "novecientos veintisiete",
    929: "novecientos veintinueve",
    932: "novecientos treinta y dos",
    935: "novecientos treinta y cinco",
    940: "novecientos cuarenta",
    950: "novecientos cincuenta",
    957: "novecientos cincuenta y siete",
    958: "novecientos cincuenta y ocho",
    959: "novecientos cincuenta y nueve",
    961: "novecientos sesenta y uno",
    966: "novecientos sesenta y seis",
    972: "novecientos setenta y dos",
    975: "novecientos setenta y cinco",
    976: "novecientos setenta y seis",
    980: "novecientos ochenta",
    984: "novecientos ochenta y cuatro",
    985: "novecientos ochenta y cinco",
    988: "novecientos ochenta y ocho",
    991: "novecientos noventa y uno",
    993: "novecientos noventa y tres",
    995: "novecientos noventa y cinco",
    999: "novecientos noventa y nueve",
    1000: "mil",
    1007: "mil siete",
    1028: "mil veintiocho",
    1036: "mil treinta y seis",
    1059: "mil cincuenta y nueve",
    1118: "mil ciento dieciocho",
    1129: "mil ciento veintinueve",
    1153: "mil ciento cincuenta y tres",
    1159: "mil ciento cincuenta y nueve",
    1242: "mil doscientos cuarenta y dos",
    1345: "mil trescientos cuarenta y cinco",
    1388: "mil trescientos ochenta y ocho",
    1407: "mil cuatrocientos siete",
    1453: "mil cuatrocientos cincuenta y tres",
    1515: "mil quinientos quince",
    1591: "mil quinientos noventa y uno",
    1627: "mil seiscientos veintisiete",
    1635: "mil seiscientos treinta y cinco",
    1652: "mil seiscientos cincuenta y dos",
    1654: "mil seiscientos cincuenta y cuatro",
    1686: "mil seiscientos ochenta y seis",
    1723: "mil setecientos veintitrés",
    1728: "mil setecientos veintiocho",
    1822: "mil ochocientos veintidós",
    1829: "mil ochocientos veintinueve",
    1833: "mil ochocientos treinta y tres",
    1888: "mil ochocientos ochenta y ocho",
    1932: "mil novecientos treinta y dos",
    1937: "mil novecientos treinta y siete",
    1950: "mil novecientos cincuenta",
    1959: "mil novecientos cincuenta y nueve",
    1961: "mil novecientos sesenta y uno",
    1965: "mil novecientos sesenta y cinco",
    1994: "mil novecientos noventa y cuatro",
    1999: "mil novecientos noventa y nueve",
    2050: "dos mil cincuenta",
    2105: "dos mil ciento cinco",
    2114: "dos mil ciento catorce",
    2123: "dos mil ciento veintitrés",
    2128: "dos mil ciento veintiocho",
    2134: "dos mil ciento treinta y cuatro",
    2138: "dos mil ciento treinta y ocho",
    2147: "dos mil ciento cuarenta y siete",
    2161: "dos mil ciento sesenta y uno",
    2164: "dos mil ciento sesenta y cuatro",
    2189: "dos mil ciento ochenta y nueve",
    2201: "dos mil doscientos uno",
    2233: "dos mil doscientos treinta y tres",
    2236: "dos mil doscientos treinta y seis",
    2291: "dos mil doscientos noventa y uno",
    2313: "dos mil trescientos trece",
    2344: "dos mil trescientos cuarenta y cuatro",
    2390: "dos mil trescientos noventa",
    2404: "dos mil cuatrocientos cuatro",
    2513: "dos mil quinientos trece",
    2529: "dos mil quinientos veintinueve",
    2546: "dos mil quinientos cuarenta y seis",
    2589: "dos mil quinientos ochenta y nueve",
    2605: "dos mil seiscientos cinco",
    2613: "dos mil seiscientos trece",
    2639: "dos mil seiscientos treinta y nueve",
    2685: "dos mil seiscientos ochenta y cinco",
    2698: "dos mil seiscientos noventa y ocho",
    2754: "dos mil setecientos cincuenta y cuatro",
    2772: "dos mil setecientos setenta y dos",
    2777: "dos mil setecientos setenta y siete",
    2791: "dos mil setecientos noventa y uno",
    2833: "dos mil ochocientos treinta y tres",
    2890: "dos mil ochocientos noventa",
    2892: "dos mil ochocientos noventa y dos",
    2895: "dos mil ochocientos noventa y cinco",
    2965: "dos mil novecientos sesenta y cinco",
    2983: "dos mil novecientos ochenta y tres",
    3042: "tres mil cuarenta y dos",
    3061: "tres mil sesenta y uno",
    3086: "tres mil ochenta y seis",
    3089: "tres mil ochenta y nueve",
    3104: "tres mil ciento cuatro",
    3144: "tres mil ciento cuarenta y cuatro",
    3145: "tres mil ciento cuarenta y cinco",
    3168: "tres mil ciento sesenta y ocho",
    3171: "tres mil ciento setenta y uno",
    3201: "tres mil doscientos uno",
    3297: "tres mil doscientos noventa y siete",
    3427: "tres mil cuatrocientos veintisiete",
    3443: "tres mil cuatrocientos cuarenta y tres",
    3533: "tres mil quinientos treinta y tres",
    3537: "tres mil quinientos treinta y siete",
    3547: "tres mil quinientos cuarenta y siete",
    3580: "tres mil quinientos ochenta",
    3585: "tres mil quinientos ochenta y cinco",
    3609: "tres mil seiscientos nueve",
    3648: "tres mil seiscientos cuarenta y ocho",
    3663: "tres mil seiscientos sesenta y tres",
    3698: "tres mil seiscientos noventa y ocho",
    3706: "tres mil setecientos seis",
    3725: "tres mil setecientos veinticinco",
    3781: "tres mil setecientos ochenta y uno",
    3852: "tres mil ochocientos cincuenta y dos",
    3901: "tres mil novecientos uno",
    3926: "tres mil novecientos veintiséis",
    3939: "tres mil novecientos treinta y nueve",
    4007: "cuatro mil siete",
    4045: "cuatro mil cuarenta y cinco",
    4112: "cuatro mil ciento doce",
    4115: "cuatro mil ciento quince",
    4117: "cuatro mil ciento diecisiete",
    4120: "cuatro mil ciento veinte",
    4140: "cuatro mil ciento cuarenta",
    4144: "cuatro mil ciento cuarenta y cuatro",
    4165: "cuatro mil ciento sesenta y cinco",
    4229: "cuatro mil doscientos veintinueve",
    4270: "cuatro mil doscientos setenta",
    4296: "cuatro mil doscientos noventa y seis",
    4336: "cuatro mil trescientos treinta y seis",
    4347: "cuatro mil trescientos cuarenta y siete",
    4442: "cuatro mil cuatrocientos cuarenta y dos",
    4444: "cuatro mil cuatrocientos cuarenta y cuatro",
    4451: "cuatro mil cuatrocientos cincuenta y uno",
    4471: "cuatro mil cuatrocientos setenta y uno",
    4493: "cuatro mil cuatrocientos noventa y tres",
    4502: "cuatro mil quinientos dos",
    4503: "cuatro mil quinientos tres",
    4511: "cuatro mil quinientos once",
    4567: "cuatro mil quinientos sesenta y siete",
    4609: "cuatro mil seiscientos nueve",
    4645: "cuatro mil seiscientos cuarenta y cinco",
    4653: "cuatro mil seiscientos cincuenta y tres",
    4682: "cuatro mil seiscientos ochenta y dos",
    4729: "cuatro mil setecientos veintinueve",
    4751: "cuatro mil setecientos cincuenta y uno",
    4771: "cuatro mil setecientos setenta y uno",
    4854: "cuatro mil ochocientos cincuenta y cuatro",
    4873: "cuatro mil ochocientos setenta y tres",
    4879: "cuatro mil ochocientos setenta y nueve",
    4900: "cuatro mil novecientos",
    4911: "cuatro mil novecientos once",
    4924: "cuatro mil novecientos veinticuatro",
    4947: "cuatro mil novecientos cuarenta y siete",
    4982: "cuatro mil novecientos ochenta y dos",
    5003: "cinco mil tres",
    5034: "cinco mil treinta y cuatro",
    5062: "cinco mil sesenta y dos",
    5066: "cinco mil sesenta y seis",
    5074: "cinco mil setenta y cuatro",
    5089: "cinco mil ochenta y nueve",
    5093: "cinco mil noventa y tres",
    5115: "cinco mil ciento quince",
    5174: "cinco mil ciento setenta y cuatro",
    5273: "cinco mil doscientos setenta y tres",
    5280: "cinco mil doscientos ochenta",
    5292: "cinco mil doscientos noventa y dos",
    5326: "cinco mil trescientos veintiséis",
    5334: "cinco mil trescientos treinta y cuatro",
    5343: "cinco mil trescientos cuarenta y tres",
    5346: "cinco mil trescientos cuarenta y seis",
    5350: "cinco mil trescientos cincuenta",
    5352: "cinco mil trescientos cincuenta y dos",
    5372: "cinco mil trescientos setenta y dos",
    5463: "cinco mil cuatrocientos sesenta y tres",
    5534: "cinco mil quinientos treinta y cuatro",
    5563: "cinco mil quinientos sesenta y tres",
    5564: "cinco mil quinientos sesenta y cuatro",
    5565: "cinco mil quinientos sesenta y cinco",
    5574: "cinco mil quinientos setenta y cuatro",
    5617: "cinco mil seiscientos diecisiete",
    5650: "cinco mil seiscientos cincuenta",
    5670: "cinco mil seiscientos setenta",
    5674: "cinco mil seiscientos setenta y cuatro",
    5701: "cinco mil setecientos uno",
    5845: "cinco mil ochocientos cuarenta y cinco",
    5862: "cinco mil ochocientos sesenta y dos",
    5906: "cinco mil novecientos seis",
    5916: "cinco mil novecientos dieciséis",
    5921: "cinco mil novecientos veintiuno",
    5931: "cinco mil novecientos treinta y uno",
    5957: "cinco mil novecientos cincuenta y siete",
    5979: "cinco mil novecientos setenta y nueve",
    6001: "seis mil uno",
    6039: "seis mil treinta y nueve",
    6051: "seis mil cincuenta y uno",
    6068: "seis mil sesenta y ocho",
    6108: "seis mil ciento ocho",
    6139: "seis mil ciento treinta y nueve",
    6140: "seis mil ciento cuarenta",
    6144: "seis mil ciento cuarenta y cuatro",
    6148: "seis mil ciento cuarenta y ocho",
    6181: "seis mil ciento ochenta y uno",
    6184: "seis mil ciento ochenta y cuatro",
    6280: "seis mil doscientos ochenta",
    6345: "seis mil trescientos cuarenta y cinco",
    6379: "seis mil trescientos setenta y nueve",
    6410: "seis mil cuatrocientos diez",
    6414: "seis mil cuatrocientos catorce",
    6426: "seis mil cuatrocientos veintiséis",
    6443: "seis mil cuatrocientos cuarenta y tres",
    6465: "seis mil cuatrocientos sesenta y cinco",
    6540: "seis mil quinientos cuarenta",
    6560: "seis mil quinientos sesenta",
    6618: "seis mil seiscientos dieciocho",
    6664: "seis mil seiscientos sesenta y cuatro",
    6719: "seis mil setecientos diecinueve",
    6729: "seis mil setecientos veintinueve",
    6754: "seis mil setecientos cincuenta y cuatro",
    6795: "seis mil setecientos noventa y cinco",
    6805: "seis mil ochocientos cinco",
    6863: "seis mil ochocientos sesenta y tres",
    6948: "seis mil novecientos cuarenta y ocho",
    6968: "seis mil novecientos sesenta y ocho",
    6975: "seis mil novecientos setenta y cinco",
    7050: "siete mil cincuenta",
    7055: "siete mil cincuenta y cinco",
    7119: "siete mil ciento diecinueve",
    7210: "siete mil doscientos diez",
    7212: "siete mil doscientos doce",
    7268: "siete mil doscientos sesenta y ocho",
    7312: "siete mil trescientos doce",
    7397: "siete mil trescientos noventa y siete",
    7485: "siete mil cuatrocientos ochenta y cinco",
    7529: "siete mil quinientos veintinueve",
    7538: "siete mil quinientos treinta y ocho",
    7549: "siete mil quinientos cuarenta y nueve",
    7571: "siete mil quinientos setenta y uno",
    7593: "siete mil quinientos noventa y tres",
    7597: "siete mil quinientos noventa y siete",
    7616: "siete mil seiscientos dieciséis",
    7654: "siete mil seiscientos cincuenta y cuatro",
    7659: "siete mil seiscientos cincuenta y nueve",
    7670: "siete mil seiscientos setenta",
    7692: "siete mil seiscientos noventa y dos",
    7736: "siete mil setecientos treinta y seis",
    7746: "siete mil setecientos cuarenta y seis",
    7756: "siete mil setecientos cincuenta y seis",
    7869: "siete mil ochocientos sesenta y nueve",
    7889: "siete mil ochocientos ochenta y nueve",
    7913: "siete mil novecientos trece",
    7931: "siete mil novecientos treinta y uno",
    7933: "siete mil novecientos treinta y tres",
    7940: "siete mil novecientos cuarenta",
    8008: "ocho mil ocho",
    8042: "ocho mil cuarenta y dos",
    8044: "ocho mil cuarenta y cuatro",
    8063: "ocho mil sesenta y tres",
    8067: "ocho mil sesenta y siete",
    8120: "ocho mil ciento veinte",
    8145: "ocho mil ciento cuarenta y cinco",
    8150: "ocho mil ciento cincuenta",
    8178: "ocho mil ciento setenta y ocho",
    8180: "ocho mil ciento ochenta",
    8239: "ocho mil doscientos treinta y nueve",
    8240: "ocho mil doscientos cuarenta",
    8245: "ocho mil doscientos cuarenta y cinco",
    8261: "ocho mil doscientos sesenta y uno",
    8351: "ocho mil trescientos cincuenta y uno",
    8398: "ocho mil trescientos noventa y ocho",
    8455: "ocho mil cuatrocientos cincuenta y cinco",
    8492: "ocho mil cuatrocientos noventa y dos",
    8509: "ocho mil quinientos nueve",
    8542: "ocho mil quinientos cuarenta y dos",
    8580: "ocho mil quinientos ochenta",
    8619: "ocho mil seiscientos diecinueve",
    8652: "ocho mil seiscientos cincuenta y dos",
    8712: "ocho mil setecientos doce",
    8745: "ocho mil setecientos cuarenta y cinco",
    8750: "ocho mil setecientos cincuenta",
    8753: "ocho mil setecientos cincuenta y tres",
    8788: "ocho mil setecientos ochenta y ocho",
    8812: "ocho mil ochocientos doce",
    8887: "ocho mil ochocientos ochenta y siete",
    8954: "ocho mil novecientos cincuenta y cuatro",
    8957: "ocho mil novecientos cincuenta y siete",
    8963: "ocho mil novecientos sesenta y tres",
    8974: "ocho mil novecientos setenta y cuatro",
    9005: "nueve mil cinco",
    9239: "nueve mil doscientos treinta y nueve",
    9281: "nueve mil doscientos ochenta y uno",
    9289: "nueve mil doscientos ochenta y nueve",
    9309: "nueve mil trescientos nueve",
    9321: "nueve mil trescientos veintiuno",
    9347: "nueve mil trescientos cuarenta y siete",
    9376: "nueve mil trescientos setenta y seis",
    9380: "nueve mil trescientos ochenta",
    9424: "nueve mil cuatrocientos veinticuatro",
    9480: "nueve mil cuatrocientos ochenta",
    9519: "nueve mil quinientos diecinueve",
    9566: "nueve mil quinientos sesenta y seis",
    9646: "nueve mil seiscientos cuarenta y seis",
    9667: "nueve mil seiscientos sesenta y siete",
    9702: "nueve mil setecientos dos",
    9728: "nueve mil setecientos veintiocho",
    9786: "nueve mil setecientos ochenta y seis",
    9787: "nueve mil setecientos ochenta y siete",
    9809: "nueve mil ochocientos nueve",
    9822: "nueve mil ochocientos veintidós",
    9835: "nueve mil ochocientos treinta y cinco",
    9836: "nueve mil ochocientos treinta y seis",
    9857: "nueve mil ochocientos cincuenta y siete",
    9884: "nueve mil ochocientos ochenta y cuatro",
    9901: "nueve mil novecientos uno",
    9939: "nueve mil novecientos treinta y nueve",
    9978: "nueve mil novecientos setenta y ocho",
    10727: "diez mil setecientos veintisiete",
    10773: "diez mil setecientos setenta y tres",
    12541: "doce mil quinientos cuarenta y uno",
    12561: "doce mil quinientos sesenta y uno",
    12672: "doce mil seiscientos setenta y dos",
    13202: "trece mil doscientos dos",
    13366: "trece mil trescientos sesenta y seis",
    13535: "trece mil quinientos treinta y cinco",
    13553: "trece mil quinientos cincuenta y tres",
    13805: "trece mil ochocientos cinco",
    14068: "catorce mil sesenta y ocho",
    15277: "quince mil doscientos setenta y siete",
    15384: "quince mil trescientos ochenta y cuatro",
    16058: "dieciséis mil cincuenta y ocho",
    16583: "dieciséis mil quinientos ochenta y tres",
    16591: "dieciséis mil quinientos noventa y uno",
    16827: "dieciséis mil ochocientos veintisiete",
    18162: "dieciocho mil ciento sesenta y dos",
    18419: "dieciocho mil cuatrocientos diecinueve",
    18994: "dieciocho mil novecientos noventa y cuatro",
    19546: "diecinueve mil quinientos cuarenta y seis",
    19962: "diecinueve mil novecientos sesenta y dos",
    20156: "veinte mil ciento cincuenta y seis",
    20562: "veinte mil quinientos sesenta y dos",
    20736: "veinte mil setecientos treinta y seis",
    21004: "veintiuno mil cuatro",
    22241: "veintidós mil doscientos cuarenta y uno",
    23357: "veintitrés mil trescientos cincuenta y siete",
    23971: "veintitrés mil novecientos setenta y uno",
    24169: "veinticuatro mil ciento sesenta y nueve",
    24994: "veinticuatro mil novecientos noventa y cuatro",
    25013: "veinticinco mil trece",
    25867: "veinticinco mil ochocientos sesenta y siete",
    25907: "veinticinco mil novecientos siete",
    26545: "veintiséis mil quinientos cuarenta y cinco",
    26729: "veintiséis mil setecientos veintinueve",
    27478: "veintisiete mil cuatrocientos setenta y ocho",
    27787: "veintisiete mil setecientos ochenta y siete",
    28137: "veintiocho mil ciento treinta y siete",
    29314: "veintinueve mil trescientos catorce",
    29343: "veintinueve mil trescientos cuarenta y tres",
    29770: "veintinueve mil setecientos setenta",
    29974: "veintinueve mil novecientos setenta y cuatro",
    30029: "treinta mil veintinueve",
    30862: "treinta mil ochocientos sesenta y dos",
    31466: "treinta y uno mil cuatrocientos sesenta y seis",
    31633: "treinta y uno mil seiscientos treinta y tres",
    31993: "treinta y uno mil novecientos noventa y tres",
    33054: "treinta y tres mil cincuenta y cuatro",
    33820: "treinta y tres mil ochocientos veinte",
    35486: "treinta y cinco mil cuatrocientos ochenta y seis",
    35996: "treinta y cinco mil novecientos noventa y seis",
    36101: "treinta y seis mil ciento uno",
    36131: "treinta y seis mil ciento treinta y uno",
    37111: "treinta y siete mil ciento once",
    37743: "treinta y siete mil setecientos cuarenta y tres",
    38044: "treinta y ocho mil cuarenta y cuatro",
    38570: "treinta y ocho mil quinientos setenta",
    38684: "treinta y ocho mil seiscientos ochenta y cuatro",
    38761: "treinta y ocho mil setecientos sesenta y uno",
    38907: "treinta y ocho mil novecientos siete",
    39390: "treinta y nueve mil trescientos noventa",
    39445: "treinta y nueve mil cuatrocientos cuarenta y cinco",
    40312: "cuarenta mil trescientos doce",
    40736: "cuarenta mil setecientos treinta y seis",
    40785: "cuarenta mil setecientos ochenta y cinco",
    41267: "cuarenta y uno mil doscientos sesenta y siete",
    41359: "cuarenta y uno mil trescientos cincuenta y nueve",
    41831: "cuarenta y uno mil ochocientos treinta y uno",
    41980: "cuarenta y uno mil novecientos ochenta",
    42093: "cuarenta y dos mil noventa y tres",
    42407: "cuarenta y dos mil cuatrocientos siete",
    42412: "cuarenta y dos mil cuatrocientos doce",
    42663: "cuarenta y dos mil seiscientos sesenta y tres",
    43066: "cuarenta y tres mil sesenta y seis",
    43587: "cuarenta y tres mil quinientos ochenta y siete",
    43973: "cuarenta y tres mil novecientos setenta y tres",
    44100: "cuarenta y cuatro mil cien",
    45615: "cuarenta y cinco mil seiscientos quince",
    45775: "cuarenta y cinco mil setecientos setenta y cinco",
    45993: "cuarenta y cinco mil novecientos noventa y tres",
    46348: "cuarenta y seis mil trescientos cuarenta y ocho",
    46472: "cuarenta y seis mil cuatrocientos setenta y dos",
    47451: "cuarenta y siete mil cuatrocientos cincuenta y uno",
    49140: "cuarenta y nueve mil ciento cuarenta",
    49530: "cuarenta y nueve mil quinientos treinta",
    50688: "cincuenta mil seiscientos ochenta y ocho",
    50769: "cincuenta mil setecientos sesenta y nueve",
    50889: "cincuenta mil ochocientos ochenta y nueve",
    51589: "cincuenta y uno mil quinientos ochenta y nueve",
    51905: "cincuenta y uno mil novecientos cinco",
    52841: "cincuenta y dos mil ochocientos cuarenta y uno",
    52907: "cincuenta y dos mil novecientos siete",
    53370: "cincuenta y tres mil trescientos setenta",
    53934: "cincuenta y tres mil novecientos treinta y cuatro",
    54021: "cincuenta y cuatro mil veintiuno",
    54058: "cincuenta y cuatro mil cincuenta y ocho",
    54237: "cincuenta y cuatro mil doscientos treinta y siete",
    55509: "cincuenta y cinco mil quinientos nueve",
    55871: "cincuenta y cinco mil ochocientos setenta y uno",
    56106: "cincuenta y seis mil ciento seis",
    58352: "cincuenta y ocho mil trescientos cincuenta y dos",
    59193: "cincuenta y nueve mil ciento noventa y tres",
    59690: "cincuenta y nueve mil seiscientos noventa",
    59693: "cincuenta y nueve mil seiscientos noventa y tres",
    59858: "cincuenta y nueve mil ochocientos cincuenta y ocho",
    60206: "sesenta mil doscientos seis",
    60329: "sesenta mil trescientos veintinueve",
    60969: "sesenta mil novecientos sesenta y nueve",
    61050: "sesenta y uno mil cincuenta",
    61117: "sesenta y uno mil ciento diecisiete",
    61646: "sesenta y uno mil seiscientos cuarenta y seis",
    61991: "sesenta y uno mil novecientos noventa y uno",
    62384: "sesenta y dos mil trescientos ochenta y cuatro",
    62995: "sesenta y dos mil novecientos noventa y cinco",
    63425: "sesenta y tres mil cuatrocientos veinticinco",
    64322: "sesenta y cuatro mil trescientos veintidós",
    64378: "sesenta y cuatro mil trescientos setenta y ocho",
    64497: "sesenta y cuatro mil cuatrocientos noventa y siete",
    64922: "sesenta y cuatro mil novecientos veintidós",
    65070: "sesenta y cinco mil setenta",
    65256: "sesenta y cinco mil doscientos cincuenta y seis",
    65725: "sesenta y cinco mil setecientos veinticinco",
    65934: "sesenta y cinco mil novecientos treinta y cuatro",
    66180: "sesenta y seis mil ciento ochenta",
    67126: "sesenta y siete mil ciento veintiséis",
    67655: "sesenta y siete mil seiscientos cincuenta y cinco",
    68009: "sesenta y ocho mil nueve",
    68447: "sesenta y ocho mil cuatrocientos cuarenta y siete",
    68992: "sesenta y ocho mil novecientos noventa y dos",
    69599: "sesenta y nueve mil quinientos noventa y nueve",
    69693: "sesenta y nueve mil seiscientos noventa y tres",
    69830: "sesenta y nueve mil ochocientos treinta",
    70516: "setenta mil quinientos dieciséis",
    70890: "setenta mil ochocientos noventa",
    70902: "setenta mil novecientos dos",
    70953: "setenta mil novecientos cincuenta y tres",
    71070: "setenta y uno mil setenta",
    71262: "setenta y uno mil doscientos sesenta y dos",
    71645: "setenta y uno mil seiscientos cuarenta y cinco",
    72071: "setenta y dos mil setenta y uno",
    72217: "setenta y dos mil doscientos diecisiete",
    72278: "setenta y dos mil doscientos setenta y ocho",
    72519: "setenta y dos mil quinientos diecinueve",
    73518: "setenta y tres mil quinientos dieciocho",
    73655: "setenta y tres mil seiscientos cincuenta y cinco",
    73994: "setenta y tres mil novecientos noventa y cuatro",
    74800: "setenta y cuatro mil ochocientos",
    76163: "setenta y seis mil ciento sesenta y tres",
    77562: "setenta y siete mil quinientos sesenta y dos",
    77890: "setenta y siete mil ochocientos noventa",
    78328: "setenta y ocho mil trescientos veintiocho",
    79617: "setenta y nueve mil seiscientos diecisiete",
    80009: "ochenta mil nueve",
    80546: "ochenta mil quinientos cuarenta y seis",
    80703: "ochenta mil setecientos tres",
    80799: "ochenta mil setecientos noventa y nueve",
    81122: "ochenta y uno mil ciento veintidós",
    81583: "ochenta y uno mil quinientos ochenta y tres",
    81811: "ochenta y uno mil ochocientos once",
    83061: "ochenta y tres mil sesenta y uno",
    83260: "ochenta y tres mil doscientos sesenta",
    83921: "ochenta y tres mil novecientos veintiuno",
    83976: "ochenta y tres mil novecientos setenta y seis",
    84178: "ochenta y cuatro mil ciento setenta y ocho",
    85455: "ochenta y cinco mil cuatrocientos cincuenta y cinco",
    85457: "ochenta y cinco mil cuatrocientos cincuenta y siete",
    85471: "ochenta y cinco mil cuatrocientos setenta y uno",
    85850: "ochenta y cinco mil ochocientos cincuenta",
    86557: "ochenta y seis mil quinientos cincuenta y siete",
    87581: "ochenta y siete mil quinientos ochenta y uno",
    87608: "ochenta y siete mil seiscientos ocho",
    88048: "ochenta y ocho mil cuarenta y ocho",
    88698: "ochenta y ocho mil seiscientos noventa y ocho",
    89070: "ochenta y nueve mil setenta",
    89416: "ochenta y nueve mil cuatrocientos dieciséis",
    89594: "ochenta y nueve mil quinientos noventa y cuatro",
    90121: "noventa mil ciento veintiuno",
    90302: "noventa mil trescientos dos",
    91168: "noventa y uno mil ciento sesenta y ocho",
    91440: "noventa y uno mil cuatrocientos cuarenta",
    91561: "noventa y uno mil quinientos sesenta y uno",
    92150: "noventa y dos mil ciento cincuenta",
    92214: "noventa y dos mil doscientos catorce",
    92545: "noventa y dos mil quinientos cuarenta y cinco",
    92961: "noventa y dos mil novecientos sesenta y uno",
    93580: "noventa y tres mil quinientos ochenta",
    94247: "noventa y cuatro mil doscientos cuarenta y siete",
    95216: "noventa y cinco mil doscientos dieciséis",
    95427: "noventa y cinco mil cuatrocientos veintisiete",
    95991: "noventa y cinco mil novecientos noventa y uno",
    96901: "noventa y seis mil novecientos uno",
    97013: "noventa y siete mil trece",
    97501: "noventa y siete mil quinientos uno",
    97671: "noventa y siete mil seiscientos setenta y uno",
    97748: "noventa y siete mil setecientos cuarenta y ocho",
    98185: "noventa y ocho mil ciento ochenta y cinco",
    98782: "noventa y ocho mil setecientos ochenta y dos",
    99017: "noventa y nueve mil diecisiete",
    99688: "noventa y nueve mil seiscientos ochenta y ocho",
    110645: "ciento diez mil seiscientos cuarenta y cinco",
    113267: "ciento trece mil doscientos sesenta y siete",
    118081: "ciento dieciocho mil ochenta y uno",
    130095: "ciento treinta mil noventa y cinco",
    172307: "ciento setenta y dos mil trescientos siete",
    189772: "ciento ochenta y nueve mil setecientos setenta y dos",
    190873: "ciento noventa mil ochocientos setenta y tres",
    197574: "ciento noventa y siete mil quinientos setenta y cuatro",
    210666: "doscientos diez mil seiscientos sesenta y seis",
    260423: "doscientos sesenta mil cuatrocientos veintitrés",
    284693: "doscientos ochenta y cuatro mil seiscientos noventa y tres",
    290673: "doscientos noventa mil seiscientos setenta y tres",
    300338: "trescientos mil trescientos treinta y ocho",
    322424: "trescientos veintidós mil cuatrocientos veinticuatro",
    332361: "trescientos treinta y dos mil trescientos sesenta y uno",
    351998: "trescientos cincuenta y uno mil novecientos noventa y ocho",
    353081: "trescientos cincuenta y tres mil ochenta y uno",
    355124: "trescientos cincuenta y cinco mil ciento veinticuatro",
    355710: "trescientos cincuenta y cinco mil setecientos diez",
    357421: "trescientos cincuenta y siete mil cuatrocientos veintiuno",
    370903: "trescientos setenta mil novecientos tres",
    381434: "trescientos ochenta y uno mil cuatrocientos treinta y cuatro",
    383202: "trescientos ochenta y tres mil doscientos dos",
    389689: "trescientos ochenta y nueve mil seiscientos ochenta y nueve",
    392478: "trescientos noventa y dos mil cuatrocientos setenta y ocho",
    393244: "trescientos noventa y tres mil doscientos cuarenta y cuatro",
    408529: "cuatrocientos ocho mil quinientos veintinueve",
    421081: "cuatrocientos veintiuno mil ochenta y uno",
    437961: "cuatrocientos treinta y siete mil novecientos sesenta y uno",
    440803: "cuatrocientos cuarenta mil ochocientos tres",
    452738: "cuatrocientos cincuenta y dos mil setecientos treinta y ocho",
    456872: "cuatrocientos cincuenta y seis mil ochocientos setenta y dos",
    457807: "cuatrocientos cincuenta y siete mil ochocientos siete",
    472061: "cuatrocientos setenta y dos mil sesenta y uno",
    479782: "cuatrocientos setenta y nueve mil setecientos ochenta y dos",
    486946: "cuatrocientos ochenta y seis mil novecientos cuarenta y seis",
    488572: "cuatrocientos ochenta y ocho mil quinientos setenta y dos",
    497400: "cuatrocientos noventa y siete mil cuatrocientos",
    524046: "quinientos veinticuatro mil cuarenta y seis",
    526171: "quinientos veintiséis mil ciento setenta y uno",
    540464: "quinientos cuarenta mil cuatrocientos sesenta y cuatro",
    549187: "quinientos cuarenta y nueve mil ciento ochenta y siete",
    554583: "quinientos cincuenta y cuatro mil quinientos ochenta y tres",
    556642: "quinientos cincuenta y seis mil seiscientos cuarenta y dos",
    556733: "quinientos cincuenta y seis mil setecientos treinta y tres",
    569946: "quinientos sesenta y nueve mil novecientos cuarenta y seis",
    572701: "quinientos setenta y dos mil setecientos uno",
    582072: "quinientos ochenta y dos mil setenta y dos",
    587283: "quinientos ochenta y siete mil doscientos ochenta y tres",
    587456: "quinientos ochenta y siete mil cuatrocientos cincuenta y seis",
    596250: "quinientos noventa y seis mil doscientos cincuenta",
    599220: "quinientos noventa y nueve mil doscientos veinte",
    606984: "seiscientos seis mil novecientos ochenta y cuatro",
    611234: "seiscientos once mil doscientos treinta y cuatro",
    612312: "seiscientos doce mil trescientos doce",
    614014: "seiscientos catorce mil catorce",
    614664: "seiscientos catorce mil seiscientos sesenta y cuatro",
    618318: "seiscientos dieciocho mil trescientos dieciocho",
    630539: "seiscientos treinta mil quinientos treinta y nueve",
    641723: "seiscientos cuarenta y uno mil setecientos veintitrés",
    647092: "seiscientos cuarenta y siete mil noventa y dos",
    658624: "seiscientos cincuenta y ocho mil seiscientos veinticuatro",
    664316: "seiscientos sesenta y cuatro mil trescientos dieciséis",
    680359: "seiscientos ochenta mil trescientos cincuenta y nueve",
    682145: "seiscientos ochenta y dos mil ciento cuarenta y cinco",
    682790: "seiscientos ochenta y dos mil setecientos noventa",
    697531: "seiscientos noventa y siete mil quinientos treinta y uno",
    709806: "setecientos nueve mil ochocientos seis",
    721255: "setecientos veintiuno mil doscientos cincuenta y cinco",
    725114: "setecientos veinticinco mil ciento catorce",
    739980: "setecientos treinta y nueve mil novecientos ochenta",
    745831: "setecientos cuarenta y cinco mil ochocientos treinta y uno",
    766460: "setecientos sesenta y seis mil cuatrocientos sesenta",
    777279: "setecientos setenta y siete mil doscientos setenta y nueve",
    778999: "setecientos setenta y ocho mil novecientos noventa y nueve",
    782055: "setecientos ochenta y dos mil cincuenta y cinco",
    793656: "setecientos noventa y tres mil seiscientos cincuenta y seis",
    796213: "setecientos noventa y seis mil doscientos trece",
    800647: "ochocientos mil seiscientos cuarenta y siete",
    824157: "ochocientos veinticuatro mil ciento cincuenta y siete",
    825392: "ochocientos veinticinco mil trescientos noventa y dos",
    835245: "ochocientos treinta y cinco mil doscientos cuarenta y cinco",
    841667: "ochocientos cuarenta y uno mil seiscientos sesenta y siete",
    846421: "ochocientos cuarenta y seis mil cuatrocientos veintiuno",
    855054: "ochocientos cincuenta y cinco mil cincuenta y cuatro",
    866537: "ochocientos sesenta y seis mil quinientos treinta y siete",
    869441: "ochocientos sesenta y nueve mil cuatrocientos cuarenta y uno",
    886932: "ochocientos ochenta y seis mil novecientos treinta y dos",
    894994: "ochocientos noventa y cuatro mil novecientos noventa y cuatro",
    912271: "novecientos doce mil doscientos setenta y uno",
    931451: "novecientos treinta y uno mil cuatrocientos cincuenta y uno",
    936588: "novecientos treinta y seis mil quinientos ochenta y ocho",
    947459: "novecientos cuarenta y siete mil cuatrocientos cincuenta y nueve",
    962277: "novecientos sesenta y dos mil doscientos setenta y siete",
    965846: "novecientos sesenta y cinco mil ochocientos cuarenta y seis",
    968963: "novecientos sesenta y ocho mil novecientos sesenta y tres",
    971085: "novecientos setenta y uno mil ochenta y cinco",
    990845: "novecientos noventa mil ochocientos cuarenta y cinco",
    992289: "novecientos noventa y dos mil doscientos ochenta y nueve",
    993086: "novecientos noventa y tres mil ochenta y seis",
    1044892: "uno millón cuarenta y cuatro mil ochocientos noventa y dos",
    1205780: "uno millón doscientos cinco mil setecientos ochenta",
    1237371: "uno millón doscientos treinta y siete mil trescientos setenta y uno",
    1547606: "uno millón quinientos cuarenta y siete mil seiscientos seis",
    1763627: "uno millón setecientos sesenta y tres mil seiscientos veintisiete",
    1861959: "uno millón ochocientos sesenta y uno mil novecientos cincuenta y nueve",
    1899412: "uno millón ochocientos noventa y nueve mil cuatrocientos doce",
    1914795: "uno millón novecientos catorce mil setecientos noventa y cinco",
    2010497: "dos millones diez mil cuatrocientos noventa y siete",
    2096281: "dos millones noventa y seis mil doscientos ochenta y uno",
    2194199: "dos millones ciento noventa y cuatro mil ciento noventa y nueve",
    2242893: "dos millones doscientos cuarenta y dos mil ochocientos noventa y tres",
    2259380: "dos millones doscientos cincuenta y nueve mil trescientos ochenta",
    2362100: "dos millones trescientos sesenta y dos mil cien",
    2429099: "dos millones cuatrocientos veintinueve mil noventa y nueve",
    2664864: "dos millones seiscientos sesenta y cuatro mil ochocientos sesenta y cuatro",
    2686549: "dos millones seiscientos ochenta y seis mil quinientos cuarenta y nueve",
    2721136: "dos millones setecientos veintiuno mil ciento treinta y seis",
    2914065: "dos millones novecientos catorce mil sesenta y cinco",
    2925627: "dos millones novecientos veinticinco mil seiscientos veintisiete",
    2987288: "dos millones novecientos ochenta y siete mil doscientos ochenta y ocho",
    3005796: "tres millones cinco mil setecientos noventa y seis",
    3024270: "tres millones veinticuatro mil doscientos setenta",
    3118619: "tres millones ciento dieciocho mil seiscientos diecinueve",
    3123710: "tres millones ciento veintitrés mil setecientos diez",
    3499628: "tres millones cuatrocientos noventa y nueve mil seiscientos veintiocho",
    3503121: "tres millones quinientos tres mil ciento veintiuno",
    3545557: "tres millones quinientos cuarenta y cinco mil quinientos cincuenta y siete",
    3626182: "tres millones seiscientos veintiséis mil ciento ochenta y dos",
    3634981: "tres millones seiscientos treinta y cuatro mil novecientos ochenta y uno",
    3916108: "tres millones novecientos dieciséis mil ciento ocho",
    4010530: "cuatro millones diez mil quinientos treinta",
    4093110: "cuatro millones noventa y tres mil ciento diez",
    4106299: "cuatro millones ciento seis mil doscientos noventa y nueve",
    4213525: "cuatro millones doscientos trece mil quinientos veinticinco",
    4231029: "cuatro millones doscientos treinta y uno mil veintinueve",
    4256753: "cuatro millones doscientos cincuenta y seis mil setecientos cincuenta y tres",
    4318856: "cuatro millones trescientos dieciocho mil ochocientos cincuenta y seis",
    4486103: "cuatro millones cuatrocientos ochenta y seis mil ciento tres",
    4540416: "cuatro millones quinientos cuarenta mil cuatrocientos dieciséis",
    4630332: "cuatro millones seiscientos treinta mil trescientos treinta y dos",
    4771677: "cuatro millones setecientos setenta y uno mil seiscientos setenta y siete",
    4786402: "cuatro millones setecientos ochenta y seis mil cuatrocientos dos",
    4816535: "cuatro millones ochocientos dieciséis mil quinientos treinta y cinco",
    4867787: "cuatro millones ochocientos sesenta y siete mil setecientos ochenta y siete",
    4883527: "cuatro millones ochocientos ochenta y tres mil quinientos veintisiete",
    4916202: "cuatro millones novecientos dieciséis mil doscientos dos",
    5024270: "cinco millones veinticuatro mil doscientos setenta",
    5163954: "cinco millones ciento sesenta y tres mil novecientos cincuenta y cuatro",
    5217854: "cinco millones doscientos diecisiete mil ochocientos cincuenta y cuatro",
    5235885: "cinco millones doscientos treinta y cinco mil ochocientos ochenta y cinco",
    5438491: "cinco millones cuatrocientos treinta y ocho mil cuatrocientos noventa y uno",
    5440026: "cinco millones cuatrocientos cuarenta mil veintiséis",
    5456574: "cinco millones cuatrocientos cincuenta y seis mil quinientos setenta y cuatro",
    5545224: "cinco millones quinientos cuarenta y cinco mil doscientos veinticuatro",
    5602181: "cinco millones seiscientos dos mil ciento ochenta y uno",
    5638894: "cinco millones seiscientos treinta y ocho mil ochocientos noventa y cuatro",
    5743228: "cinco millones setecientos cuarenta y tres mil doscientos veintiocho",
    5747931: "cinco millones setecientos cuarenta y siete mil novecientos treinta y uno",
    5770423: "cinco millones setecientos setenta mil cuatrocientos veintitrés",
    5833598: "cinco millones ochocientos treinta y tres mil quinientos noventa y ocho",
    5886521: "cinco millones ochocientos ochenta y seis mil quinientos veintiuno",
    5901240: "cinco millones novecientos uno mil doscientos cuarenta",
    5970191: "cinco millones novecientos setenta mil ciento noventa y uno",
    5988758: "cinco millones novecientos ochenta y ocho mil setecientos cincuenta y ocho",
    6071209: "seis millones setenta y uno mil doscientos nueve",
    6097515: "seis millones noventa y siete mil quinientos quince",
    6123431: "seis millones ciento veintitrés mil cuatrocientos treinta y uno",
    6144281: "seis millones ciento cuarenta y cuatro mil doscientos ochenta y uno",
    6294017: "seis millones doscientos noventa y cuatro mil diecisiete",
    6549758: "seis millones quinientos cuarenta y nueve mil setecientos cincuenta y ocho",
    6716098: "seis millones setecientos dieciséis mil noventa y ocho",
    6767293: "seis millones setecientos sesenta y siete mil doscientos noventa y tres",
    6902402: "seis millones novecientos dos mil cuatrocientos dos",
    7054580: "siete millones cincuenta y cuatro mil quinientos ochenta",
    7381685: "siete millones trescientos ochenta y uno mil seiscientos ochenta y cinco",
    7722756: "siete millones setecientos veintidós mil setecientos cincuenta y seis",
    7853788: "siete millones ochocientos cincuenta y tres mil setecientos ochenta y ocho",
    7982242: "siete millones novecientos ochenta y dos mil doscientos cuarenta y dos",
    8132649: "ocho millones ciento treinta y dos mil seiscientos cuarenta y nueve",
    8138770: "ocho millones ciento treinta y ocho mil setecientos setenta",
    8194571: "ocho millones ciento noventa y cuatro mil quinientos setenta y uno",
    8389841: "ocho millones trescientos ochenta y nueve mil ochocientos cuarenta y uno",
    8427626: "ocho millones cuatrocientos veintisiete mil seiscientos veintiséis",
    8558198: "ocho millones quinientos cincuenta y ocho mil ciento noventa y ocho",
    8558379: "ocho millones quinientos cincuenta y ocho mil trescientos setenta y nueve",
    8612583: "ocho millones seiscientos doce mil quinientos ochenta y tres",
    8617382: "ocho millones seiscientos diecisiete mil trescientos ochenta y dos",
    8875174: "ocho millones ochocientos setenta y cinco mil ciento setenta y cuatro",
    8883824: "ocho millones ochocientos ochenta y tres mil ochocientos veinticuatro",
    9014966: "nueve millones catorce mil novecientos sesenta y seis",
    9031492: "nueve millones treinta y uno mil cuatrocientos noventa y dos",
    9123505: "nueve millones ciento veintitrés mil quinientos cinco",
    9235578: "nueve millones doscientos treinta y cinco mil quinientos setenta y ocho",
    9250139: "nueve millones doscientos cincuenta mil ciento treinta y nueve",
    9767313: "nueve millones setecientos sesenta y siete mil trescientos trece",
    9801947: "nueve millones ochocientos uno mil novecientos cuarenta y siete",
    9907392: "nueve millones novecientos siete mil trescientos noventa y dos",
    9961300: "nueve millones novecientos sesenta y uno mil trescientos",
    9990306: "nueve millones novecientos noventa mil trescientos seis",
}
