"""add verb_cards table

Revision ID: 0bc6214a6f78
Revises: a7c3f4e91b22
Create Date: 2026-06-23 08:13:02.574018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc6214a6f78'
down_revision = 'a7c3f4e91b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verb_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_sub', sa.String(length=255), nullable=False),
    sa.Column('infinitive', sa.String(length=64), nullable=False),
    sa.Column('times_practiced', sa.Integer(), server_default='0', nullable=False),
    sa.Column('times_correct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recent_results', sa.String(length=10), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verb_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verb_cards_user_sub'), ['user_sub'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verb_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verb_cards_user_sub'))

    op.drop_table('verb_cards')
    # ### end Alembic commands ###
