"""add conjugation_stats table

Revision ID: 0c25ab8f74fd
Revises: 0bc6214a6f78
Create Date: 2026-06-23 17:44:52.073311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c25ab8f74fd'
down_revision = '0bc6214a6f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conjugation_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_sub', sa.String(length=255), nullable=False),
    sa.Column('tense_key', sa.String(length=64), nullable=False),
    sa.Column('person_index', sa.Integer(), nullable=False),
    sa.Column('times_practiced', sa.Integer(), server_default='0', nullable=False),
    sa.Column('times_correct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_sub', 'tense_key', 'person_index', name='uq_conjstat_dim')
    )
    with op.batch_alter_table('conjugation_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conjugation_stats_user_sub'), ['user_sub'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conjugation_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conjugation_stats_user_sub'))

    op.drop_table('conjugation_stats')
    # ### end Alembic commands ###
