"""add card scoring counters

Revision ID: 1ba2818cd571
Revises: cad4adf84d71
Create Date: 2026-05-11 07:11:07.546007

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ba2818cd571"
down_revision = "cad4adf84d71"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "times_practiced", sa.Integer(), server_default="0", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("times_correct", sa.Integer(), server_default="0", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_column("times_correct")
        batch_op.drop_column("times_practiced")

    # ### end Alembic commands ###
