"""add lang to verb_cards and conjugation_stats

Revision ID: 5bcdb98cd1e9
Revises: 0c25ab8f74fd
Create Date: 2026-07-14 21:36:39.105302

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5bcdb98cd1e9"
down_revision = "0c25ab8f74fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conjugation_stats", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("lang", sa.String(length=8), server_default="es", nullable=False)
        )
        batch_op.drop_constraint(batch_op.f("uq_conjstat_dim"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_conjstat_dim", ["user_sub", "lang", "tense_key", "person_index"]
        )

    with op.batch_alter_table("verb_cards", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("lang", sa.String(length=8), server_default="es", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verb_cards", schema=None) as batch_op:
        batch_op.drop_column("lang")

    with op.batch_alter_table("conjugation_stats", schema=None) as batch_op:
        batch_op.drop_constraint("uq_conjstat_dim", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_conjstat_dim"), ["user_sub", "tense_key", "person_index"]
        )
        batch_op.drop_column("lang")

    # ### end Alembic commands ###
