"""initial cards table

Revision ID: cad4adf84d71
Revises:
Create Date: 2026-04-25 09:38:43.008221

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cad4adf84d71"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_sub", sa.String(length=255), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cards_user_sub"), ["user_sub"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cards_user_sub"))

    op.drop_table("cards")
    # ### end Alembic commands ###
