"""add poll_responses table

Revision ID: e5f9dc9f4bd4
Revises: ddf4f587fb5f
Create Date: 2026-05-14 09:14:16.737725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f9dc9f4bd4'
down_revision = 'ddf4f587fb5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_sub', sa.String(length=255), nullable=True),
    sa.Column('color_scheme_pref', sa.String(length=16), nullable=False),
    sa.Column('cards_aware', sa.String(length=16), nullable=False),
    sa.Column('device', sa.String(length=16), nullable=False),
    sa.Column('freeform', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_responses_user_sub'), ['user_sub'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_responses_user_sub'))

    op.drop_table('poll_responses')
    # ### end Alembic commands ###
